# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='promedio21',
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
    ]
