# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_codigo_promedio21'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='promedio2',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio22',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio3',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio31',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio32',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio4',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio41',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio42',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio43',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
    ]
