# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20180606_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='promedio5',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio51',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio52',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio6',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio61',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio610',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio62',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio63',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio64',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio65',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio66',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio67',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio68',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio69',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
