# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-08 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20180607_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='promedio011',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio10',
            field=models.CharField(default=50, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio101',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio111',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio112',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio113',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio7',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio71',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio72',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio73',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio74',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio75',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio76',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio77',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio8',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio81',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio82',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio83',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio84',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio85',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio86',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio9',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio91',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='promedio92',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
