from django.db import models

class Codigo(models.Model):
    codigo = models.CharField(max_length=30)
    promedio11 = models.CharField(max_length=30)
    promedio2 = models.CharField(max_length=30)
    promedio21 = models.CharField(max_length=30)
    promedio22 = models.CharField(max_length=30)
    promedio3 = models.CharField(max_length=30)
    promedio31 = models.CharField(max_length=30)
    promedio32 = models.CharField(max_length=30)
    promedio4 = models.CharField(max_length=30)
    promedio41 = models.CharField(max_length=30)
    promedio42 = models.CharField(max_length=30)
    promedio43 = models.CharField(max_length=30)
    promedio5 = models.CharField(max_length=30)
    promedio51 = models.CharField(max_length=30)
    promedio52 = models.CharField(max_length=30)
    promedio6 = models.CharField(max_length=30)
    promedio61 = models.CharField(max_length=30)
    promedio62 = models.CharField(max_length=30)
    promedio63 = models.CharField(max_length=30)
    promedio64 = models.CharField(max_length=30)
    promedio65 = models.CharField(max_length=30)
    promedio66 = models.CharField(max_length=30)
    promedio67 = models.CharField(max_length=30)
    promedio68 = models.CharField(max_length=30)
    promedio69 = models.CharField(max_length=30)
    promedio610 = models.CharField(max_length=30)
    promedio7 = models.CharField(max_length=30)
    promedio71 = models.CharField(max_length=30)
    promedio72 = models.CharField(max_length=30)
    promedio73 = models.CharField(max_length=30)
    promedio74 = models.CharField(max_length=30)
    promedio75 = models.CharField(max_length=30)
    promedio76 = models.CharField(max_length=30)
    promedio77 = models.CharField(max_length=30)
    promedio8 = models.CharField(max_length=30)
    promedio81 = models.CharField(max_length=30)
    promedio82 = models.CharField(max_length=30)
    promedio83 = models.CharField(max_length=30)
    promedio84 = models.CharField(max_length=30)
    promedio85 = models.CharField(max_length=30)
    promedio86 = models.CharField(max_length=30)
    promedio9 = models.CharField(max_length=30)
    promedio91 = models.CharField(max_length=30)
    promedio92 = models.CharField(max_length=30)
    promedio10 = models.CharField(max_length=30)
    promedio101 = models.CharField(max_length=30)
    promedio011 = models.CharField(max_length=30)
    promedio111 = models.CharField(max_length=30)
    promedio112 = models.CharField(max_length=30)
    promedio113 = models.CharField(max_length=30)






